### ISSUE TITLE
Unable to Build (Help)

### ISSUE THREAD

**Issue by kurisubrooks** [jaboles/DVA5#17]
I generally wouldn't discuss such a thing in GitHub Issues, but I haven't been able to find an attached Twitter account to your profile, and you don't appear to have "Discussions" enabled for the repository, so please excuse me for this informal issue.

Following the instructions on the build instructions link (included in the README), I'm unable to get `ant` to build the app successfully on macOS. 

Running `ant BuildMacApp` yields the following error log.
Note that `/Users/kurisu/Developer/DVA5/` is the cloned repository (master branch).

I'd appreciate any help you're able to provide.

```sh
❯ ant BuildMacApp
Buildfile: /Users/kurisu/Developer/DVA5/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found.

Compile:

BUILD FAILED
/Users/kurisu/Developer/DVA5/build.xml:147: Execute failed: java.io.IOException: Cannot run program "protoc" (in directory "/Users/kurisu/Developer/DVA5"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:818)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 24 more

Total time: 0 seconds
```

**Comment by jaboles** [comment]
Hey,
the build now uses some additional tasks from ant-contrib. Try running "brew install --ignore-dependencies ant-contrib"

**Comment by kurisubrooks** [comment]
Just installed `ant-contrib` but I'm still getting the same error (without the "missing" definitions this time, however)

```
❯ brew install --ignore-dependencies ant-contrib
Running `brew update --preinstall`...
==> Downloading
==> Pouring ant-contrib--1.0b3.all.bottle.tar.gz
🍺  /opt/homebrew/Cellar/ant-contrib/1.0b3: 257 files, 3.4MB
==> Running `brew cleanup ant-contrib`...

❯ ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021

❯ ant BuildMacApp
Buildfile: /Users/kurisu/Developer/DVA5/build.xml

Compile:

BUILD FAILED
/Users/kurisu/Developer/DVA5/build.xml:147: Execute failed: java.io.IOException: Cannot run program "protoc" (in directory "/Users/kurisu/Developer/DVA5"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:818)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 24 more

Total time: 0 seconds
```

**Comment by jaboles** [comment]
'protoc' is Google's protocol buffers compiler, used to generate Java classes for accessing GTFS data. I don't remember how I set it up (may have eventually built it from source) but I will soon update the documentation with the procedure.

**Comment by jaboles** [comment]
There are pre-built ProtoC binaries here: https://github.com/protocolbuffers/protobuf/releases/ (files beginning with 'protoc') I think I used that.

**Comment by jaboles** [comment]
If you update to the latest sources and rerun 'ant FetchDeps' it will now download protoc to the tools folder and use it to compile.

**Comment by kurisubrooks** [comment]
Got further in the build process this time, now failing at fakeroot for being deprecated;
Truncated irrelevant parts.

```
❯ ant FetchDeps
Buildfile: /Users/kurisu/Developer/DVA5/build.xml

FetchDeps.Common:
      ...

FetchDeps.Mac:
     ...
     [exec] Warning: fakeroot has been deprecated because it does not build!
     [exec] Error: fakeroot: no bottle available!
     [exec] You can try to install from source with:
     [exec]   brew install --build-from-source fakeroot
     [exec] Please note building from source is unsupported. You will encounter build
     [exec] failures with some formulae. If you experience any issues please create pull
     [exec] requests instead of asking for help on Homebrew's GitHub, Twitter or any other
     [exec] official channels.

BUILD FAILED
/Users/kurisu/Developer/DVA5/build.xml:119: exec returned: 1

Total time: 3 seconds

❯ brew install --build-from-source fakeroot
Warning: fakeroot has been deprecated because it does not build!
==> Downloading https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=5;filename=0001-Implement-openat-2
-#O#- #   #                                                                   
==> Downloading https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=5;filename=0002-OS-X-10.10-introdu
######################################################################## 100.0%
==> Downloading https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
curl: (22) The requested URL returned error: 404                              

Error: fakeroot: Failed to download resource "fakeroot"
Download failed: https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.24.orig.tar.gz
```

**Comment by kurisubrooks** [comment]
Also another note; Wine doesn't run on ARM64. (M1)

```
BUILD FAILED
/Users/kurisu/Developer/DVA5/build.xml:110: Execute failed: java.io.IOException: Cannot run program "wine" (in directory "/Users/kurisu/Developer/DVA5"): error=86, Bad CPU type in executable
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
	at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:818)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: error=86, Bad CPU type in executable
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 24 more
```

**Comment by kurisubrooks** [comment]
After some hacky workarounds to get it to run through my installed version of Java (17, build uses 11), it appears FFmpeg requires the LAME encoding to be installed, but this isn't installed through the package, so no sound is produced.

Let me know if you want a new issue for this bug.
```
13:17:31.417 [Thread-17] INFO  j.c.s.MediaConcatenatorFfmpeg - Running ffmpeg: /Users/kurisu/Developer/DVA5/build/Output/DVA.app/Contents/MacOS/ffmpeg -i 0 -i 1 -i 2 -i 3 -i 4 -i 5 -i 6 -i 7 -i 8 -i 9 -i 10 -i 11 -i 12 -i 13 -i 14 -i 15 -i 16 -i 17 -i 18 -i 19 -i 20 -i 21 -i 22 -i 23 -i 24 -i 25 -i 26 -i 27 -filter_complex [0:0][1:0][2:0][3:0][4:0][5:0][6:0][7:0][8:0][9:0][10:0][11:0][12:0][13:0][14:0][15:0][16:0][17:0][18:0][19:0][20:0][21:0][22:0][23:0][24:0][25:0][26:0][27:0]concat=n=28:v=0:a=1[out] -map [out] -codec:a libmp3lame -q:a 2 /var/folders/m5/z6f47_052pgd9h221fq_73nm0000gn/T/DVA/PlayerCache/8556059533954008243.temp.mp3
13:17:31.426 [Thread-21] DEBUG j.c.s.MediaConcatenatorFfmpeg - dyld[41393]: Library not loaded: /usr/local/opt/lame/lib/libmp3lame.0.dylib
13:17:31.427 [Thread-21] DEBUG j.c.s.MediaConcatenatorFfmpeg -   Referenced from: /Users/kurisu/Developer/DVA5/build/Output/DVA.app/Contents/MacOS/ffmpeg
13:17:31.427 [Thread-21] DEBUG j.c.s.MediaConcatenatorFfmpeg -   Reason: tried: '/usr/local/opt/lame/lib/libmp3lame.0.dylib' (no such file), '/usr/local/lib/libmp3lame.0.dylib' (no such file), '/usr/lib/libmp3lame.0.dylib' (no such file)
```

**Comment by jaboles** [comment]
Eh. interesting. I thought I had built it static so that libmp3lame would be included. Will need to do some more experimentation.

**Comment by jaboles** [comment]
I modified the method to build FFmpeg and they should be static now.

**Comment by kurisubrooks** [comment]
Works now. Thank you so much!
