### ISSUE TITLE
Launching indicator for Central Station with no platform selected fails

### ISSUE THREAD

**Issue by Petarkco** [jaboles/DVA5#20]
Selecting Central Station with no specific platform to display an indicator fails.

Screenshot of settings:
![image](https://user-images.githubusercontent.com/25685344/153846854-f4aa0b37-9a60-4b37-a0bb-72d7dee6bf5e.png)

Log:
`java.lang.IllegalStateException: Duplicate key null (attempted merging values {} and {})
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at jb.plasma.gtfs.GtfsTimetableTranslator.refreshRealtimeInfo(GtfsTimetableTranslator.java:227)
        at jb.plasma.gtfs.GtfsTimetableTranslator$1.run(GtfsTimetableTranslator.java:36)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)`

**Comment by jaboles** [comment]
Thank you for the report. This will be fixed in the next release.
