### ISSUE TITLE
Some announcements failing to play

### ISSUE THREAD

**Issue by MLVDau** [jaboles/DVA5#8]
Version 5.3.6, in the timetable section of indicators, 

This appears in the log:
`04/03/2017 12:09:37.311 [jb.plasma.ui.PlasmaUI.announce] [INFO] - Playing auto generated announcement
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at jb.plasma.Phraser.getVia(Phraser.java:50)
        at jb.plasma.announcers.CityrailStandard.createAnnouncementText(CityrailStandard.java:48)
        at jb.plasma.Announcer.createAnnouncement(Announcer.java:36)
        at jb.plasma.ui.PlasmaUI.announce(PlasmaUI.java:408)
        at jb.plasma.ui.PlasmaUI$5.actionPerformed(PlasmaUI.java:552)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(Unknown Source)
        at javax.swing.SwingUtilities.notifyAction(Unknown Source)
        at javax.swing.JComponent.processKeyBinding(Unknown Source)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
        at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
        at javax.swing.JMenuBar.processKeyBinding(Unknown Source)
        at javax.swing.KeyboardManager.fireBinding(Unknown Source)
        at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
        at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
        at javax.swing.SwingUtilities.processKeyBindings(Unknown Source)
        at javax.swing.UIManager$2.postProcessKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by jaboles** [comment]
Thanks for reporting. I fixed this bug in 197a0c7 / 5.3.11.
